#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_SIDNEY      0
#define MUGSHOT_PHOEBE      1
#define MUGSHOT_GLACIA      2
#define MUGSHOT_DRAKE       3
#define MUGSHOT_CHAMPION    4
#define MUGSHOT_MAY         5
#define MUGSHOT_BRENDAN     6
#define MUGSHOT_WALLY       7

#define MUGSHOTS_COUNT      8

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H