	.align 2
gTilesetPalOverrides_General::
	.byte 1             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_General05

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Petalburg::
	.byte 6             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Petalburg06

	.byte 8             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Petalburg08

	.byte 9             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Petalburg09

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Rustboro::
	.byte 6             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Rustboro06

	.byte 10            @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Rustboro10

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Mauville::
	.byte 10            @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Mauville10

	.byte 7             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Mauville07

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Lavaridge::
	.byte 6             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Lavaridge06

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Slateport::
	.byte 8             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_General01

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Fortree::
	.byte 8             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Fortree08

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

gTilesetPalOverrides_Lilycove::
	.byte 6             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Lilycove06

	.byte 9             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_Lilycove09

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Mossdeep::
	.byte 8             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_General05

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_EverGrande::
	.byte 7             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_EverGrande07

	.byte 8             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_General05

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_BattleFrontierOutsideWest::
	.byte 6             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_BattleFrontierOutside06

	.byte 9             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_BattleFrontierOutsideWest09

	.byte 11             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_BattleFrontierOutsideWest11

	.byte 12             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_BattleFrontierOutsideWest12

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_BattleFrontierOutsideEast::
	.byte 6             @ palette index
	.byte HOUR_NIGHT    @ start hour (inclusive)
	.byte HOUR_MORNING  @ end hour (exclusive)
	.byte 0             @ padding
	.4byte gTilesetPalOverride_BattleFrontierOutside06

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

